//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/smial/MyRepos/rsl-bis/AntlrCSharp/RslBis.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="RslBisParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IRslBisVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStart([NotNull] RslBisParser.StartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.usecase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsecase([NotNull] RslBisParser.UsecaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.ucconditions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUcconditions([NotNull] RslBisParser.UcconditionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.conditions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditions([NotNull] RslBisParser.ConditionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] RslBisParser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.mainscenario"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMainscenario([NotNull] RslBisParser.MainscenarioContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.scenarios"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScenarios([NotNull] RslBisParser.ScenariosContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.scenario"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScenario([NotNull] RslBisParser.ScenarioContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.sentences"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentences([NotNull] RslBisParser.SentencesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.altsentences"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAltsentences([NotNull] RslBisParser.AltsentencesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.sentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentence([NotNull] RslBisParser.SentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.altsentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAltsentence([NotNull] RslBisParser.AltsentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.condsentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondsentence([NotNull] RslBisParser.CondsentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.endsentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndsentence([NotNull] RslBisParser.EndsentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.resultsentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResultsentence([NotNull] RslBisParser.ResultsentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.rejoinsentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRejoinsentence([NotNull] RslBisParser.RejoinsentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.result"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResult([NotNull] RslBisParser.ResultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.repsentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepsentence([NotNull] RslBisParser.RepsentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.svosentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSvosentence([NotNull] RslBisParser.SvosentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.altsvosentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAltsvosentence([NotNull] RslBisParser.AltsvosentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.step"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStep([NotNull] RslBisParser.StepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.systemstep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSystemstep([NotNull] RslBisParser.SystemstepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.toactorpredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToactorpredicate([NotNull] RslBisParser.ToactorpredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.showpredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShowpredicate([NotNull] RslBisParser.ShowpredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.closepredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClosepredicate([NotNull] RslBisParser.ClosepredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.tosystempredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTosystempredicate([NotNull] RslBisParser.TosystempredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.readpredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadpredicate([NotNull] RslBisParser.ReadpredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.updatepredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdatepredicate([NotNull] RslBisParser.UpdatepredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.deletepredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeletepredicate([NotNull] RslBisParser.DeletepredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.validatepredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValidatepredicate([NotNull] RslBisParser.ValidatepredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.executepredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExecutepredicate([NotNull] RslBisParser.ExecutepredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.userstep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUserstep([NotNull] RslBisParser.UserstepContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.selectpredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectpredicate([NotNull] RslBisParser.SelectpredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.enterpredicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnterpredicate([NotNull] RslBisParser.EnterpredicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.invoke"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInvoke([NotNull] RslBisParser.InvokeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.dnotion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDnotion([NotNull] RslBisParser.DnotionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.attributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributes([NotNull] RslBisParser.AttributesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] RslBisParser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.actor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActor([NotNull] RslBisParser.ActorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.notion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotion([NotNull] RslBisParser.NotionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] RslBisParser.NameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel([NotNull] RslBisParser.LabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="RslBisParser.altlabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAltlabel([NotNull] RslBisParser.AltlabelContext context);
}
