//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/smial/MyRepos/rsl-bis/AntlrCSharp/RslBis.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class RslBisParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		NUMBER=32, CHAR=33, STRING=34, WS=35;
	public const int
		RULE_start = 0, RULE_usecase = 1, RULE_ucconditions = 2, RULE_conditions = 3, 
		RULE_condition = 4, RULE_contextcondition = 5, RULE_valuecondition = 6, 
		RULE_mainscenario = 7, RULE_scenarios = 8, RULE_scenario = 9, RULE_sentences = 10, 
		RULE_altsentences = 11, RULE_sentence = 12, RULE_altsentence = 13, RULE_condsentence = 14, 
		RULE_endsentence = 15, RULE_resultsentence = 16, RULE_rejoinsentence = 17, 
		RULE_result = 18, RULE_repsentence = 19, RULE_svosentence = 20, RULE_altsvosentence = 21, 
		RULE_step = 22, RULE_systemstep = 23, RULE_toactorpredicate = 24, RULE_showpredicate = 25, 
		RULE_closepredicate = 26, RULE_tosystempredicate = 27, RULE_readpredicate = 28, 
		RULE_updatepredicate = 29, RULE_deletepredicate = 30, RULE_checkpredicate = 31, 
		RULE_executepredicate = 32, RULE_userstep = 33, RULE_selectpredicate = 34, 
		RULE_enterpredicate = 35, RULE_invoke = 36, RULE_dnotion = 37, RULE_attributes = 38, 
		RULE_attribute = 39, RULE_actor = 40, RULE_notion = 41, RULE_value = 42, 
		RULE_name = 43, RULE_label = 44, RULE_altlabel = 45, RULE_labelref = 46;
	public static readonly string[] ruleNames = {
		"start", "usecase", "ucconditions", "conditions", "condition", "contextcondition", 
		"valuecondition", "mainscenario", "scenarios", "scenario", "sentences", 
		"altsentences", "sentence", "altsentence", "condsentence", "endsentence", 
		"resultsentence", "rejoinsentence", "result", "repsentence", "svosentence", 
		"altsvosentence", "step", "systemstep", "toactorpredicate", "showpredicate", 
		"closepredicate", "tosystempredicate", "readpredicate", "updatepredicate", 
		"deletepredicate", "checkpredicate", "executepredicate", "userstep", "selectpredicate", 
		"enterpredicate", "invoke", "dnotion", "attributes", "attribute", "actor", 
		"notion", "value", "name", "label", "altlabel", "labelref"
	};

	private static readonly string[] _LiteralNames = {
		null, "'Use case'", "'{'", "'}'", "';'", "'user'", "'?'", "'Main scenario'", 
		"'Scenario'", "'['", "']'", "'->'", "'end'", "'!'", "'rejoin'", "'-\"-'", 
		"'System'", "'<show>'", "'<close>'", "'<read>'", "'<update>'", "'<delete>'", 
		"'<check>'", "'<execute>'", "'<select>'", "'<enter>'", "'<invoke>'", "'Frame'", 
		"'Trigger'", "'Data'", "':'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, "NUMBER", "CHAR", "STRING", 
		"WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "RslBis.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static RslBisParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public RslBisParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public RslBisParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class StartContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(RslBisParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public UsecaseContext[] usecase() {
			return GetRuleContexts<UsecaseContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public UsecaseContext usecase(int i) {
			return GetRuleContext<UsecaseContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DnotionContext[] dnotion() {
			return GetRuleContexts<DnotionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public DnotionContext dnotion(int i) {
			return GetRuleContext<DnotionContext>(i);
		}
		public StartContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_start; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStart(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StartContext start() {
		StartContext _localctx = new StartContext(Context, State);
		EnterRule(_localctx, 0, RULE_start);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 95;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 94;
				usecase();
				}
				}
				State = 97;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==T__0 );
			State = 102;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 939524096L) != 0)) {
				{
				{
				State = 99;
				dnotion();
				}
				}
				State = 104;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 105;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UsecaseContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NameContext name() {
			return GetRuleContext<NameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MainscenarioContext mainscenario() {
			return GetRuleContext<MainscenarioContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ScenariosContext scenarios() {
			return GetRuleContext<ScenariosContext>(0);
		}
		public UsecaseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_usecase; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUsecase(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UsecaseContext usecase() {
		UsecaseContext _localctx = new UsecaseContext(Context, State);
		EnterRule(_localctx, 2, RULE_usecase);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 107;
			Match(T__0);
			State = 108;
			name();
			State = 109;
			mainscenario();
			State = 111;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__7) {
				{
				State = 110;
				scenarios();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UcconditionsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ConditionsContext conditions() {
			return GetRuleContext<ConditionsContext>(0);
		}
		public UcconditionsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ucconditions; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUcconditions(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UcconditionsContext ucconditions() {
		UcconditionsContext _localctx = new UcconditionsContext(Context, State);
		EnterRule(_localctx, 4, RULE_ucconditions);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 113;
			Match(T__1);
			State = 114;
			conditions();
			State = 115;
			Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConditionsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ConditionContext condition() {
			return GetRuleContext<ConditionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConditionsContext conditions() {
			return GetRuleContext<ConditionsContext>(0);
		}
		public ConditionsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_conditions; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConditions(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConditionsContext conditions() {
		ConditionsContext _localctx = new ConditionsContext(Context, State);
		EnterRule(_localctx, 6, RULE_conditions);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 117;
			condition();
			State = 120;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__3) {
				{
				State = 118;
				Match(T__3);
				State = 119;
				conditions();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConditionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueconditionContext valuecondition() {
			return GetRuleContext<ValueconditionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ContextconditionContext contextcondition() {
			return GetRuleContext<ContextconditionContext>(0);
		}
		public ConditionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condition; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCondition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConditionContext condition() {
		ConditionContext _localctx = new ConditionContext(Context, State);
		EnterRule(_localctx, 8, RULE_condition);
		try {
			State = 124;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 122;
				valuecondition();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 123;
				contextcondition();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ContextconditionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NotionContext notion() {
			return GetRuleContext<NotionContext>(0);
		}
		public ContextconditionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_contextcondition; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitContextcondition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ContextconditionContext contextcondition() {
		ContextconditionContext _localctx = new ContextconditionContext(Context, State);
		EnterRule(_localctx, 10, RULE_contextcondition);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 126;
			notion();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueconditionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NotionContext notion() {
			return GetRuleContext<NotionContext>(0);
		}
		public ValueconditionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_valuecondition; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitValuecondition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ValueconditionContext valuecondition() {
		ValueconditionContext _localctx = new ValueconditionContext(Context, State);
		EnterRule(_localctx, 12, RULE_valuecondition);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 130;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__4:
				{
				State = 128;
				Match(T__4);
				}
				break;
			case STRING:
				{
				State = 129;
				notion();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 132;
			Match(T__5);
			State = 133;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MainscenarioContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SentencesContext sentences() {
			return GetRuleContext<SentencesContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public EndsentenceContext endsentence() {
			return GetRuleContext<EndsentenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public UcconditionsContext ucconditions() {
			return GetRuleContext<UcconditionsContext>(0);
		}
		public MainscenarioContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mainscenario; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMainscenario(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MainscenarioContext mainscenario() {
		MainscenarioContext _localctx = new MainscenarioContext(Context, State);
		EnterRule(_localctx, 14, RULE_mainscenario);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 135;
			Match(T__6);
			State = 137;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__1) {
				{
				State = 136;
				ucconditions();
				}
			}

			State = 139;
			sentences();
			State = 140;
			endsentence();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ScenariosContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ScenarioContext scenario() {
			return GetRuleContext<ScenarioContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ScenariosContext scenarios() {
			return GetRuleContext<ScenariosContext>(0);
		}
		public ScenariosContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_scenarios; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitScenarios(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ScenariosContext scenarios() {
		ScenariosContext _localctx = new ScenariosContext(Context, State);
		EnterRule(_localctx, 16, RULE_scenarios);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 142;
			scenario();
			State = 144;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__7) {
				{
				State = 143;
				scenarios();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ScenarioContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RepsentenceContext repsentence() {
			return GetRuleContext<RepsentenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AltsentencesContext altsentences() {
			return GetRuleContext<AltsentencesContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public EndsentenceContext endsentence() {
			return GetRuleContext<EndsentenceContext>(0);
		}
		public ScenarioContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_scenario; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitScenario(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ScenarioContext scenario() {
		ScenarioContext _localctx = new ScenarioContext(Context, State);
		EnterRule(_localctx, 18, RULE_scenario);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 146;
			Match(T__7);
			State = 147;
			repsentence();
			State = 148;
			altsentences();
			State = 149;
			endsentence();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SentencesContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SentenceContext sentence() {
			return GetRuleContext<SentenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SentencesContext sentences() {
			return GetRuleContext<SentencesContext>(0);
		}
		public SentencesContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_sentences; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSentences(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SentencesContext sentences() {
		SentencesContext _localctx = new SentencesContext(Context, State);
		EnterRule(_localctx, 20, RULE_sentences);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 151;
			sentence();
			State = 153;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__8 || _la==NUMBER) {
				{
				State = 152;
				sentences();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AltsentencesContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AltsentenceContext altsentence() {
			return GetRuleContext<AltsentenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AltsentencesContext altsentences() {
			return GetRuleContext<AltsentencesContext>(0);
		}
		public AltsentencesContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_altsentences; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAltsentences(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AltsentencesContext altsentences() {
		AltsentencesContext _localctx = new AltsentencesContext(Context, State);
		EnterRule(_localctx, 22, RULE_altsentences);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 155;
			altsentence();
			State = 157;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__8 || _la==CHAR) {
				{
				State = 156;
				altsentences();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SentenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SvosentenceContext svosentence() {
			return GetRuleContext<SvosentenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CondsentenceContext condsentence() {
			return GetRuleContext<CondsentenceContext>(0);
		}
		public SentenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_sentence; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSentence(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SentenceContext sentence() {
		SentenceContext _localctx = new SentenceContext(Context, State);
		EnterRule(_localctx, 24, RULE_sentence);
		try {
			State = 161;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NUMBER:
				EnterOuterAlt(_localctx, 1);
				{
				State = 159;
				svosentence();
				}
				break;
			case T__8:
				EnterOuterAlt(_localctx, 2);
				{
				State = 160;
				condsentence();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AltsentenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AltsvosentenceContext altsvosentence() {
			return GetRuleContext<AltsvosentenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CondsentenceContext condsentence() {
			return GetRuleContext<CondsentenceContext>(0);
		}
		public AltsentenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_altsentence; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAltsentence(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AltsentenceContext altsentence() {
		AltsentenceContext _localctx = new AltsentenceContext(Context, State);
		EnterRule(_localctx, 26, RULE_altsentence);
		try {
			State = 165;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case CHAR:
				EnterOuterAlt(_localctx, 1);
				{
				State = 163;
				altsvosentence();
				}
				break;
			case T__8:
				EnterOuterAlt(_localctx, 2);
				{
				State = 164;
				condsentence();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CondsentenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ConditionsContext conditions() {
			return GetRuleContext<ConditionsContext>(0);
		}
		public CondsentenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condsentence; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCondsentence(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CondsentenceContext condsentence() {
		CondsentenceContext _localctx = new CondsentenceContext(Context, State);
		EnterRule(_localctx, 28, RULE_condsentence);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 167;
			Match(T__8);
			State = 168;
			conditions();
			State = 169;
			Match(T__9);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EndsentenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ResultsentenceContext resultsentence() {
			return GetRuleContext<ResultsentenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RejoinsentenceContext rejoinsentence() {
			return GetRuleContext<RejoinsentenceContext>(0);
		}
		public EndsentenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_endsentence; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEndsentence(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EndsentenceContext endsentence() {
		EndsentenceContext _localctx = new EndsentenceContext(Context, State);
		EnterRule(_localctx, 30, RULE_endsentence);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 171;
			Match(T__10);
			State = 174;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__11:
				{
				State = 172;
				resultsentence();
				}
				break;
			case T__13:
				{
				State = 173;
				rejoinsentence();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ResultsentenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public ResultsentenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_resultsentence; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitResultsentence(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ResultsentenceContext resultsentence() {
		ResultsentenceContext _localctx = new ResultsentenceContext(Context, State);
		EnterRule(_localctx, 32, RULE_resultsentence);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 176;
			Match(T__11);
			State = 177;
			Match(T__12);
			State = 178;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RejoinsentenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public LabelrefContext labelref() {
			return GetRuleContext<LabelrefContext>(0);
		}
		public RejoinsentenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rejoinsentence; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRejoinsentence(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RejoinsentenceContext rejoinsentence() {
		RejoinsentenceContext _localctx = new RejoinsentenceContext(Context, State);
		EnterRule(_localctx, 34, RULE_rejoinsentence);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 180;
			Match(T__13);
			State = 181;
			labelref();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ResultContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(RslBisParser.STRING, 0); }
		public ResultContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_result; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitResult(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ResultContext result() {
		ResultContext _localctx = new ResultContext(Context, State);
		EnterRule(_localctx, 36, RULE_result);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 183;
			Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RepsentenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public LabelContext label() {
			return GetRuleContext<LabelContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AltlabelContext altlabel() {
			return GetRuleContext<AltlabelContext>(0);
		}
		public RepsentenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_repsentence; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRepsentence(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RepsentenceContext repsentence() {
		RepsentenceContext _localctx = new RepsentenceContext(Context, State);
		EnterRule(_localctx, 38, RULE_repsentence);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 187;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NUMBER:
				{
				State = 185;
				label();
				}
				break;
			case CHAR:
				{
				State = 186;
				altlabel();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 189;
			Match(T__14);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SvosentenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public LabelContext label() {
			return GetRuleContext<LabelContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StepContext step() {
			return GetRuleContext<StepContext>(0);
		}
		public SvosentenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_svosentence; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSvosentence(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SvosentenceContext svosentence() {
		SvosentenceContext _localctx = new SvosentenceContext(Context, State);
		EnterRule(_localctx, 40, RULE_svosentence);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 191;
			label();
			State = 192;
			step();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AltsvosentenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AltlabelContext altlabel() {
			return GetRuleContext<AltlabelContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StepContext step() {
			return GetRuleContext<StepContext>(0);
		}
		public AltsvosentenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_altsvosentence; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAltsvosentence(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AltsvosentenceContext altsvosentence() {
		AltsvosentenceContext _localctx = new AltsvosentenceContext(Context, State);
		EnterRule(_localctx, 42, RULE_altsvosentence);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 194;
			altlabel();
			State = 195;
			step();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StepContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public UserstepContext userstep() {
			return GetRuleContext<UserstepContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SystemstepContext systemstep() {
			return GetRuleContext<SystemstepContext>(0);
		}
		public StepContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_step; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStep(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StepContext step() {
		StepContext _localctx = new StepContext(Context, State);
		EnterRule(_localctx, 44, RULE_step);
		try {
			State = 199;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case STRING:
				EnterOuterAlt(_localctx, 1);
				{
				State = 197;
				userstep();
				}
				break;
			case T__15:
				EnterOuterAlt(_localctx, 2);
				{
				State = 198;
				systemstep();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SystemstepContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TosystempredicateContext tosystempredicate() {
			return GetRuleContext<TosystempredicateContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ToactorpredicateContext toactorpredicate() {
			return GetRuleContext<ToactorpredicateContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public InvokeContext invoke() {
			return GetRuleContext<InvokeContext>(0);
		}
		public SystemstepContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_systemstep; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSystemstep(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SystemstepContext systemstep() {
		SystemstepContext _localctx = new SystemstepContext(Context, State);
		EnterRule(_localctx, 46, RULE_systemstep);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 201;
			Match(T__15);
			State = 205;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__18:
			case T__19:
			case T__20:
			case T__21:
			case T__22:
				{
				State = 202;
				tosystempredicate();
				}
				break;
			case T__16:
			case T__17:
				{
				State = 203;
				toactorpredicate();
				}
				break;
			case T__25:
				{
				State = 204;
				invoke();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ToactorpredicateContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ShowpredicateContext showpredicate() {
			return GetRuleContext<ShowpredicateContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ClosepredicateContext closepredicate() {
			return GetRuleContext<ClosepredicateContext>(0);
		}
		public ToactorpredicateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_toactorpredicate; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitToactorpredicate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ToactorpredicateContext toactorpredicate() {
		ToactorpredicateContext _localctx = new ToactorpredicateContext(Context, State);
		EnterRule(_localctx, 48, RULE_toactorpredicate);
		try {
			State = 209;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__16:
				EnterOuterAlt(_localctx, 1);
				{
				State = 207;
				showpredicate();
				}
				break;
			case T__17:
				EnterOuterAlt(_localctx, 2);
				{
				State = 208;
				closepredicate();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ShowpredicateContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NotionContext notion() {
			return GetRuleContext<NotionContext>(0);
		}
		public ShowpredicateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_showpredicate; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitShowpredicate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ShowpredicateContext showpredicate() {
		ShowpredicateContext _localctx = new ShowpredicateContext(Context, State);
		EnterRule(_localctx, 50, RULE_showpredicate);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 211;
			Match(T__16);
			State = 212;
			notion();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ClosepredicateContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NotionContext notion() {
			return GetRuleContext<NotionContext>(0);
		}
		public ClosepredicateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_closepredicate; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitClosepredicate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ClosepredicateContext closepredicate() {
		ClosepredicateContext _localctx = new ClosepredicateContext(Context, State);
		EnterRule(_localctx, 52, RULE_closepredicate);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 214;
			Match(T__17);
			State = 215;
			notion();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TosystempredicateContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ReadpredicateContext readpredicate() {
			return GetRuleContext<ReadpredicateContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public UpdatepredicateContext updatepredicate() {
			return GetRuleContext<UpdatepredicateContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DeletepredicateContext deletepredicate() {
			return GetRuleContext<DeletepredicateContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CheckpredicateContext checkpredicate() {
			return GetRuleContext<CheckpredicateContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExecutepredicateContext executepredicate() {
			return GetRuleContext<ExecutepredicateContext>(0);
		}
		public TosystempredicateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_tosystempredicate; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTosystempredicate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TosystempredicateContext tosystempredicate() {
		TosystempredicateContext _localctx = new TosystempredicateContext(Context, State);
		EnterRule(_localctx, 54, RULE_tosystempredicate);
		try {
			State = 222;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__18:
				EnterOuterAlt(_localctx, 1);
				{
				State = 217;
				readpredicate();
				}
				break;
			case T__19:
				EnterOuterAlt(_localctx, 2);
				{
				State = 218;
				updatepredicate();
				}
				break;
			case T__20:
				EnterOuterAlt(_localctx, 3);
				{
				State = 219;
				deletepredicate();
				}
				break;
			case T__21:
				EnterOuterAlt(_localctx, 4);
				{
				State = 220;
				checkpredicate();
				}
				break;
			case T__22:
				EnterOuterAlt(_localctx, 5);
				{
				State = 221;
				executepredicate();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReadpredicateContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NotionContext notion() {
			return GetRuleContext<NotionContext>(0);
		}
		public ReadpredicateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_readpredicate; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReadpredicate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ReadpredicateContext readpredicate() {
		ReadpredicateContext _localctx = new ReadpredicateContext(Context, State);
		EnterRule(_localctx, 56, RULE_readpredicate);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 224;
			Match(T__18);
			State = 225;
			notion();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UpdatepredicateContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NotionContext notion() {
			return GetRuleContext<NotionContext>(0);
		}
		public UpdatepredicateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_updatepredicate; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUpdatepredicate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UpdatepredicateContext updatepredicate() {
		UpdatepredicateContext _localctx = new UpdatepredicateContext(Context, State);
		EnterRule(_localctx, 58, RULE_updatepredicate);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 227;
			Match(T__19);
			State = 228;
			notion();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DeletepredicateContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NotionContext notion() {
			return GetRuleContext<NotionContext>(0);
		}
		public DeletepredicateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_deletepredicate; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDeletepredicate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DeletepredicateContext deletepredicate() {
		DeletepredicateContext _localctx = new DeletepredicateContext(Context, State);
		EnterRule(_localctx, 60, RULE_deletepredicate);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 230;
			Match(T__20);
			State = 231;
			notion();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CheckpredicateContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NotionContext notion() {
			return GetRuleContext<NotionContext>(0);
		}
		public CheckpredicateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_checkpredicate; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCheckpredicate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CheckpredicateContext checkpredicate() {
		CheckpredicateContext _localctx = new CheckpredicateContext(Context, State);
		EnterRule(_localctx, 62, RULE_checkpredicate);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 233;
			Match(T__21);
			State = 234;
			notion();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExecutepredicateContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NotionContext notion() {
			return GetRuleContext<NotionContext>(0);
		}
		public ExecutepredicateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_executepredicate; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExecutepredicate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExecutepredicateContext executepredicate() {
		ExecutepredicateContext _localctx = new ExecutepredicateContext(Context, State);
		EnterRule(_localctx, 64, RULE_executepredicate);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 236;
			Match(T__22);
			State = 237;
			notion();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UserstepContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ActorContext actor() {
			return GetRuleContext<ActorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SelectpredicateContext selectpredicate() {
			return GetRuleContext<SelectpredicateContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public EnterpredicateContext enterpredicate() {
			return GetRuleContext<EnterpredicateContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public InvokeContext invoke() {
			return GetRuleContext<InvokeContext>(0);
		}
		public UserstepContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_userstep; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUserstep(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UserstepContext userstep() {
		UserstepContext _localctx = new UserstepContext(Context, State);
		EnterRule(_localctx, 66, RULE_userstep);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 239;
			actor();
			State = 243;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__23:
				{
				State = 240;
				selectpredicate();
				}
				break;
			case T__24:
				{
				State = 241;
				enterpredicate();
				}
				break;
			case T__25:
				{
				State = 242;
				invoke();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SelectpredicateContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NotionContext notion() {
			return GetRuleContext<NotionContext>(0);
		}
		public SelectpredicateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_selectpredicate; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSelectpredicate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SelectpredicateContext selectpredicate() {
		SelectpredicateContext _localctx = new SelectpredicateContext(Context, State);
		EnterRule(_localctx, 68, RULE_selectpredicate);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 245;
			Match(T__23);
			State = 246;
			notion();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EnterpredicateContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NotionContext notion() {
			return GetRuleContext<NotionContext>(0);
		}
		public EnterpredicateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enterpredicate; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEnterpredicate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EnterpredicateContext enterpredicate() {
		EnterpredicateContext _localctx = new EnterpredicateContext(Context, State);
		EnterRule(_localctx, 70, RULE_enterpredicate);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 248;
			Match(T__24);
			State = 249;
			notion();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InvokeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NameContext name() {
			return GetRuleContext<NameContext>(0);
		}
		public InvokeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_invoke; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInvoke(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InvokeContext invoke() {
		InvokeContext _localctx = new InvokeContext(Context, State);
		EnterRule(_localctx, 72, RULE_invoke);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 251;
			Match(T__25);
			State = 252;
			name();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DnotionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STRING() { return GetTokens(RslBisParser.STRING); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING(int i) {
			return GetToken(RslBisParser.STRING, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AttributesContext attributes() {
			return GetRuleContext<AttributesContext>(0);
		}
		public DnotionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dnotion; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDnotion(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DnotionContext dnotion() {
		DnotionContext _localctx = new DnotionContext(Context, State);
		EnterRule(_localctx, 74, RULE_dnotion);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 254;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 939524096L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 256;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 255;
				Match(STRING);
				}
				}
				State = 258;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==STRING );
			State = 266;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__29:
				{
				{
				State = 260;
				Match(T__29);
				State = 261;
				Match(STRING);
				}
				}
				break;
			case T__1:
				{
				{
				State = 262;
				Match(T__1);
				State = 263;
				attributes();
				State = 264;
				Match(T__2);
				}
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AttributesContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AttributeContext attribute() {
			return GetRuleContext<AttributeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AttributesContext attributes() {
			return GetRuleContext<AttributesContext>(0);
		}
		public AttributesContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_attributes; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAttributes(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AttributesContext attributes() {
		AttributesContext _localctx = new AttributesContext(Context, State);
		EnterRule(_localctx, 76, RULE_attributes);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 268;
			attribute();
			State = 271;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__30) {
				{
				State = 269;
				Match(T__30);
				State = 270;
				attributes();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AttributeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STRING() { return GetTokens(RslBisParser.STRING); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING(int i) {
			return GetToken(RslBisParser.STRING, i);
		}
		public AttributeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_attribute; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAttribute(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AttributeContext attribute() {
		AttributeContext _localctx = new AttributeContext(Context, State);
		EnterRule(_localctx, 78, RULE_attribute);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 274;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 273;
				Match(STRING);
				}
				}
				State = 276;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==STRING );
			State = 278;
			Match(T__29);
			State = 279;
			Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ActorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(RslBisParser.STRING, 0); }
		public ActorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_actor; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitActor(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ActorContext actor() {
		ActorContext _localctx = new ActorContext(Context, State);
		EnterRule(_localctx, 80, RULE_actor);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 281;
			Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NotionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STRING() { return GetTokens(RslBisParser.STRING); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING(int i) {
			return GetToken(RslBisParser.STRING, i);
		}
		public NotionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_notion; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNotion(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NotionContext notion() {
		NotionContext _localctx = new NotionContext(Context, State);
		EnterRule(_localctx, 82, RULE_notion);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 284;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 283;
				Match(STRING);
				}
				}
				State = 286;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==STRING );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STRING() { return GetTokens(RslBisParser.STRING); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING(int i) {
			return GetToken(RslBisParser.STRING, i);
		}
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 84, RULE_value);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 289;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 288;
				Match(STRING);
				}
				}
				State = 291;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==STRING );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STRING() { return GetTokens(RslBisParser.STRING); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING(int i) {
			return GetToken(RslBisParser.STRING, i);
		}
		public NameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_name; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NameContext name() {
		NameContext _localctx = new NameContext(Context, State);
		EnterRule(_localctx, 86, RULE_name);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 294;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 293;
				Match(STRING);
				}
				}
				State = 296;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==STRING );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LabelContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(RslBisParser.NUMBER, 0); }
		public LabelContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_label; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLabel(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LabelContext label() {
		LabelContext _localctx = new LabelContext(Context, State);
		EnterRule(_localctx, 88, RULE_label);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 298;
			Match(NUMBER);
			State = 299;
			Match(T__29);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AltlabelContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CHAR() { return GetToken(RslBisParser.CHAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(RslBisParser.NUMBER, 0); }
		public AltlabelContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_altlabel; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAltlabel(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AltlabelContext altlabel() {
		AltlabelContext _localctx = new AltlabelContext(Context, State);
		EnterRule(_localctx, 90, RULE_altlabel);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 301;
			Match(CHAR);
			State = 302;
			Match(NUMBER);
			State = 303;
			Match(T__29);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LabelrefContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(RslBisParser.NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CHAR() { return GetToken(RslBisParser.CHAR, 0); }
		public LabelrefContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_labelref; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IRslBisVisitor<TResult> typedVisitor = visitor as IRslBisVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLabelref(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LabelrefContext labelref() {
		LabelrefContext _localctx = new LabelrefContext(Context, State);
		EnterRule(_localctx, 92, RULE_labelref);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 306;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==CHAR) {
				{
				State = 305;
				Match(CHAR);
				}
			}

			State = 308;
			Match(NUMBER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,35,311,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,2,27,7,27,2,28,7,28,
		2,29,7,29,2,30,7,30,2,31,7,31,2,32,7,32,2,33,7,33,2,34,7,34,2,35,7,35,
		2,36,7,36,2,37,7,37,2,38,7,38,2,39,7,39,2,40,7,40,2,41,7,41,2,42,7,42,
		2,43,7,43,2,44,7,44,2,45,7,45,2,46,7,46,1,0,4,0,96,8,0,11,0,12,0,97,1,
		0,5,0,101,8,0,10,0,12,0,104,9,0,1,0,1,0,1,1,1,1,1,1,1,1,3,1,112,8,1,1,
		2,1,2,1,2,1,2,1,3,1,3,1,3,3,3,121,8,3,1,4,1,4,3,4,125,8,4,1,5,1,5,1,6,
		1,6,3,6,131,8,6,1,6,1,6,1,6,1,7,1,7,3,7,138,8,7,1,7,1,7,1,7,1,8,1,8,3,
		8,145,8,8,1,9,1,9,1,9,1,9,1,9,1,10,1,10,3,10,154,8,10,1,11,1,11,3,11,158,
		8,11,1,12,1,12,3,12,162,8,12,1,13,1,13,3,13,166,8,13,1,14,1,14,1,14,1,
		14,1,15,1,15,1,15,3,15,175,8,15,1,16,1,16,1,16,1,16,1,17,1,17,1,17,1,18,
		1,18,1,19,1,19,3,19,188,8,19,1,19,1,19,1,20,1,20,1,20,1,21,1,21,1,21,1,
		22,1,22,3,22,200,8,22,1,23,1,23,1,23,1,23,3,23,206,8,23,1,24,1,24,3,24,
		210,8,24,1,25,1,25,1,25,1,26,1,26,1,26,1,27,1,27,1,27,1,27,1,27,3,27,223,
		8,27,1,28,1,28,1,28,1,29,1,29,1,29,1,30,1,30,1,30,1,31,1,31,1,31,1,32,
		1,32,1,32,1,33,1,33,1,33,1,33,3,33,244,8,33,1,34,1,34,1,34,1,35,1,35,1,
		35,1,36,1,36,1,36,1,37,1,37,4,37,257,8,37,11,37,12,37,258,1,37,1,37,1,
		37,1,37,1,37,1,37,3,37,267,8,37,1,38,1,38,1,38,3,38,272,8,38,1,39,4,39,
		275,8,39,11,39,12,39,276,1,39,1,39,1,39,1,40,1,40,1,41,4,41,285,8,41,11,
		41,12,41,286,1,42,4,42,290,8,42,11,42,12,42,291,1,43,4,43,295,8,43,11,
		43,12,43,296,1,44,1,44,1,44,1,45,1,45,1,45,1,45,1,46,3,46,307,8,46,1,46,
		1,46,1,46,0,0,47,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,
		40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,
		88,90,92,0,1,1,0,27,29,295,0,95,1,0,0,0,2,107,1,0,0,0,4,113,1,0,0,0,6,
		117,1,0,0,0,8,124,1,0,0,0,10,126,1,0,0,0,12,130,1,0,0,0,14,135,1,0,0,0,
		16,142,1,0,0,0,18,146,1,0,0,0,20,151,1,0,0,0,22,155,1,0,0,0,24,161,1,0,
		0,0,26,165,1,0,0,0,28,167,1,0,0,0,30,171,1,0,0,0,32,176,1,0,0,0,34,180,
		1,0,0,0,36,183,1,0,0,0,38,187,1,0,0,0,40,191,1,0,0,0,42,194,1,0,0,0,44,
		199,1,0,0,0,46,201,1,0,0,0,48,209,1,0,0,0,50,211,1,0,0,0,52,214,1,0,0,
		0,54,222,1,0,0,0,56,224,1,0,0,0,58,227,1,0,0,0,60,230,1,0,0,0,62,233,1,
		0,0,0,64,236,1,0,0,0,66,239,1,0,0,0,68,245,1,0,0,0,70,248,1,0,0,0,72,251,
		1,0,0,0,74,254,1,0,0,0,76,268,1,0,0,0,78,274,1,0,0,0,80,281,1,0,0,0,82,
		284,1,0,0,0,84,289,1,0,0,0,86,294,1,0,0,0,88,298,1,0,0,0,90,301,1,0,0,
		0,92,306,1,0,0,0,94,96,3,2,1,0,95,94,1,0,0,0,96,97,1,0,0,0,97,95,1,0,0,
		0,97,98,1,0,0,0,98,102,1,0,0,0,99,101,3,74,37,0,100,99,1,0,0,0,101,104,
		1,0,0,0,102,100,1,0,0,0,102,103,1,0,0,0,103,105,1,0,0,0,104,102,1,0,0,
		0,105,106,5,0,0,1,106,1,1,0,0,0,107,108,5,1,0,0,108,109,3,86,43,0,109,
		111,3,14,7,0,110,112,3,16,8,0,111,110,1,0,0,0,111,112,1,0,0,0,112,3,1,
		0,0,0,113,114,5,2,0,0,114,115,3,6,3,0,115,116,5,3,0,0,116,5,1,0,0,0,117,
		120,3,8,4,0,118,119,5,4,0,0,119,121,3,6,3,0,120,118,1,0,0,0,120,121,1,
		0,0,0,121,7,1,0,0,0,122,125,3,12,6,0,123,125,3,10,5,0,124,122,1,0,0,0,
		124,123,1,0,0,0,125,9,1,0,0,0,126,127,3,82,41,0,127,11,1,0,0,0,128,131,
		5,5,0,0,129,131,3,82,41,0,130,128,1,0,0,0,130,129,1,0,0,0,131,132,1,0,
		0,0,132,133,5,6,0,0,133,134,3,84,42,0,134,13,1,0,0,0,135,137,5,7,0,0,136,
		138,3,4,2,0,137,136,1,0,0,0,137,138,1,0,0,0,138,139,1,0,0,0,139,140,3,
		20,10,0,140,141,3,30,15,0,141,15,1,0,0,0,142,144,3,18,9,0,143,145,3,16,
		8,0,144,143,1,0,0,0,144,145,1,0,0,0,145,17,1,0,0,0,146,147,5,8,0,0,147,
		148,3,38,19,0,148,149,3,22,11,0,149,150,3,30,15,0,150,19,1,0,0,0,151,153,
		3,24,12,0,152,154,3,20,10,0,153,152,1,0,0,0,153,154,1,0,0,0,154,21,1,0,
		0,0,155,157,3,26,13,0,156,158,3,22,11,0,157,156,1,0,0,0,157,158,1,0,0,
		0,158,23,1,0,0,0,159,162,3,40,20,0,160,162,3,28,14,0,161,159,1,0,0,0,161,
		160,1,0,0,0,162,25,1,0,0,0,163,166,3,42,21,0,164,166,3,28,14,0,165,163,
		1,0,0,0,165,164,1,0,0,0,166,27,1,0,0,0,167,168,5,9,0,0,168,169,3,6,3,0,
		169,170,5,10,0,0,170,29,1,0,0,0,171,174,5,11,0,0,172,175,3,32,16,0,173,
		175,3,34,17,0,174,172,1,0,0,0,174,173,1,0,0,0,175,31,1,0,0,0,176,177,5,
		12,0,0,177,178,5,13,0,0,178,179,3,84,42,0,179,33,1,0,0,0,180,181,5,14,
		0,0,181,182,3,92,46,0,182,35,1,0,0,0,183,184,5,34,0,0,184,37,1,0,0,0,185,
		188,3,88,44,0,186,188,3,90,45,0,187,185,1,0,0,0,187,186,1,0,0,0,188,189,
		1,0,0,0,189,190,5,15,0,0,190,39,1,0,0,0,191,192,3,88,44,0,192,193,3,44,
		22,0,193,41,1,0,0,0,194,195,3,90,45,0,195,196,3,44,22,0,196,43,1,0,0,0,
		197,200,3,66,33,0,198,200,3,46,23,0,199,197,1,0,0,0,199,198,1,0,0,0,200,
		45,1,0,0,0,201,205,5,16,0,0,202,206,3,54,27,0,203,206,3,48,24,0,204,206,
		3,72,36,0,205,202,1,0,0,0,205,203,1,0,0,0,205,204,1,0,0,0,206,47,1,0,0,
		0,207,210,3,50,25,0,208,210,3,52,26,0,209,207,1,0,0,0,209,208,1,0,0,0,
		210,49,1,0,0,0,211,212,5,17,0,0,212,213,3,82,41,0,213,51,1,0,0,0,214,215,
		5,18,0,0,215,216,3,82,41,0,216,53,1,0,0,0,217,223,3,56,28,0,218,223,3,
		58,29,0,219,223,3,60,30,0,220,223,3,62,31,0,221,223,3,64,32,0,222,217,
		1,0,0,0,222,218,1,0,0,0,222,219,1,0,0,0,222,220,1,0,0,0,222,221,1,0,0,
		0,223,55,1,0,0,0,224,225,5,19,0,0,225,226,3,82,41,0,226,57,1,0,0,0,227,
		228,5,20,0,0,228,229,3,82,41,0,229,59,1,0,0,0,230,231,5,21,0,0,231,232,
		3,82,41,0,232,61,1,0,0,0,233,234,5,22,0,0,234,235,3,82,41,0,235,63,1,0,
		0,0,236,237,5,23,0,0,237,238,3,82,41,0,238,65,1,0,0,0,239,243,3,80,40,
		0,240,244,3,68,34,0,241,244,3,70,35,0,242,244,3,72,36,0,243,240,1,0,0,
		0,243,241,1,0,0,0,243,242,1,0,0,0,244,67,1,0,0,0,245,246,5,24,0,0,246,
		247,3,82,41,0,247,69,1,0,0,0,248,249,5,25,0,0,249,250,3,82,41,0,250,71,
		1,0,0,0,251,252,5,26,0,0,252,253,3,86,43,0,253,73,1,0,0,0,254,256,7,0,
		0,0,255,257,5,34,0,0,256,255,1,0,0,0,257,258,1,0,0,0,258,256,1,0,0,0,258,
		259,1,0,0,0,259,266,1,0,0,0,260,261,5,30,0,0,261,267,5,34,0,0,262,263,
		5,2,0,0,263,264,3,76,38,0,264,265,5,3,0,0,265,267,1,0,0,0,266,260,1,0,
		0,0,266,262,1,0,0,0,267,75,1,0,0,0,268,271,3,78,39,0,269,270,5,31,0,0,
		270,272,3,76,38,0,271,269,1,0,0,0,271,272,1,0,0,0,272,77,1,0,0,0,273,275,
		5,34,0,0,274,273,1,0,0,0,275,276,1,0,0,0,276,274,1,0,0,0,276,277,1,0,0,
		0,277,278,1,0,0,0,278,279,5,30,0,0,279,280,5,34,0,0,280,79,1,0,0,0,281,
		282,5,34,0,0,282,81,1,0,0,0,283,285,5,34,0,0,284,283,1,0,0,0,285,286,1,
		0,0,0,286,284,1,0,0,0,286,287,1,0,0,0,287,83,1,0,0,0,288,290,5,34,0,0,
		289,288,1,0,0,0,290,291,1,0,0,0,291,289,1,0,0,0,291,292,1,0,0,0,292,85,
		1,0,0,0,293,295,5,34,0,0,294,293,1,0,0,0,295,296,1,0,0,0,296,294,1,0,0,
		0,296,297,1,0,0,0,297,87,1,0,0,0,298,299,5,32,0,0,299,300,5,30,0,0,300,
		89,1,0,0,0,301,302,5,33,0,0,302,303,5,32,0,0,303,304,5,30,0,0,304,91,1,
		0,0,0,305,307,5,33,0,0,306,305,1,0,0,0,306,307,1,0,0,0,307,308,1,0,0,0,
		308,309,5,32,0,0,309,93,1,0,0,0,27,97,102,111,120,124,130,137,144,153,
		157,161,165,174,187,199,205,209,222,243,258,266,271,276,286,291,296,306
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
