///////////////////////////////////////////////////////////
//  Call.cs
//  Implementation of the Class Call
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:54
//  Original author: smial
///////////////////////////////////////////////////////////




using CodeModel;
namespace CodeModel {
	public class Call : Instruction {

		public CodeModel.UCCallableOperation operation;

		public Call(){

		}

		~Call(){

		}

	}//end Call

}//end namespace CodeModel