///////////////////////////////////////////////////////////
//  Call.cs
//  Implementation of the Class Call
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:54
//  Original author: smial
///////////////////////////////////////////////////////////

namespace CodeModel {
	public class Call : Instruction {

		public UCCallableOperation operation;

		public Call(){}
	}
}