///////////////////////////////////////////////////////////
//  Enumeration.cs
//  Implementation of the Class Enumeration
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:54
//  Original author: smial
///////////////////////////////////////////////////////////

using System.Collections.Generic;
namespace CodeModel {
	public class CheckEnumeration : NamedElement {
		public List<Value> values = new List<Value>();

		public CheckEnumeration(){}
	}
}