///////////////////////////////////////////////////////////
//  Enumeration.cs
//  Implementation of the Class Enumeration
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:54
//  Original author: smial
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Linq;
namespace CodeModel {
	public class CheckEnumeration : NamedElement {
		public List<Value> values = new List<Value>();

		public CheckEnumeration(){}

		public string GetElemName(){
            return Utils.ToPascalCase(name.Replace("!", ""));
        }

		public string GetVarName(){
            return Utils.ToCamelCase(name.Replace("!", ""));
        }

		public string ToCode(int tabs = 0){
			string ts = Utils.GetTabString(tabs);
			string code = ts + "export enum " + GetElemName() + " {\n";
			code += string.Join(",\n", values.Select(v => ts + "\t" + v.GetElemName() + " = \"" + v.GetElemName() + "\"")) + "\n";
			code += ts + "}\n";
			return code;
		}
	}
}