///////////////////////////////////////////////////////////
//  ClassFIleGenerator.cs
//  Implementation of the Class ClassFIleGenerator
//  Generated by Enterprise Architect
//  Created on:      02-lut-2024 18:09:12
//  Original author: smial
///////////////////////////////////////////////////////////

using CodeModel;
public abstract class ClassFileGenerator : FileGenerator {
	public ClassFileGenerator(){}
	public abstract string GetVarName();
}