///////////////////////////////////////////////////////////
//  Condition.cs
//  Implementation of the Class Condition
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:54
//  Original author: smial
///////////////////////////////////////////////////////////




using CodeModel;
namespace CodeModel {
	public class Condition {

		public CodeModel.Instruction instructions;
		public CodeModel.Expression expressions;

		public Condition(){

		}

		~Condition(){

		}

	}//end Condition

}//end namespace CodeModel