///////////////////////////////////////////////////////////
//  Condition.cs
//  Implementation of the Class Condition
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:54
//  Original author: smial
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Linq;
namespace CodeModel {
	public class Condition {

		public List<Instruction> instructions = new List<Instruction>();
		public List<Expression> expressions = new List<Expression>();

		public Condition(){}

		public string ToCode(int tabs){
			string ts = Utils.GetTabString(tabs);
			// CODE: if (ClientEnumCheck.Valid == clientEnumCheck) {
            string code = "if (" + string.Join(" && ", expressions.Select(e => e.ToCode())) + ") {\n";
			foreach (Instruction instr in instructions)
                code += instr.ToCode(tabs + 1) + "\n";
			code += ts + "}";
			return code;
        }
	}

}