///////////////////////////////////////////////////////////
//  Condition.cs
//  Implementation of the Class Condition
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:54
//  Original author: smial
///////////////////////////////////////////////////////////

using System.Collections.Generic;
namespace CodeModel {
	public class Condition {

		public List<Instruction> instructions = new List<Instruction>();
		public List<Expression> expressions = new List<Expression>();

		public Condition(){}
	}

}