///////////////////////////////////////////////////////////
//  ControllerFunction.cs
//  Implementation of the Class ControllerFunction
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:54
//  Original author: smial
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Linq;
namespace CodeModel {
	public class ControllerFunction : FileGenerator {
		public List<COperation> functions = new List<COperation>();
		public List<UseCaseClass> useCases = new List<UseCaseClass>();

		public ControllerFunction(){}

        public override string GetElemName(){
            return "C" + Utils.ToPascalCase(name);
        }

        public override string ToCode(int tabs){
            string ts = Utils.GetTabString(tabs);
            // export function CCLientListForm(
            string code = ts + "export function " + GetElemName() + "(\n";
            //   state: ClientListFormData,
            code += ts + "\tstate: " + Utils.ToPascalCase(name) + "State,\n\t" + ts;
            //   showClientList: UCShowClientList
            code += string.Join(",\n\t" + ts, useCases.Select(x => x.GetVarName() + ": " + x.GetElemName()));
            // ) {
            code += "\n) {\n" + ts;
            //   >>>sub-functions<<<
            code += string.Join("\n" + ts,functions.Select(x => x.ToCode(tabs + 1)));
            //   return [selectClose, selectFindClient, invokeCheckFindClient];
            code += "\n\t" + ts + "return [" + string.Join(", ", functions.Select(x => x.GetElemName())) + "];\n" + ts + "}";
            return code;
        }

        protected override string GetFileName(){
            return "C " + name;
        }

    }
}