///////////////////////////////////////////////////////////
//  ControllerFunction.cs
//  Implementation of the Class ControllerFunction
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:54
//  Original author: smial
///////////////////////////////////////////////////////////




using CodeModel;
namespace CodeModel {
	public class ControllerFunction : NamedElement {

		public CodeModel.COperation functions;
		public CodeModel.UseCaseClass useCases;

		public ControllerFunction(){

		}

		~ControllerFunction(){

		}

	}//end ControllerFunction

}//end namespace CodeModel