///////////////////////////////////////////////////////////
//  COperation.cs
//  Implementation of the Class COperation
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:54
//  Original author: smial
///////////////////////////////////////////////////////////




using CodeModel;
namespace CodeModel {
	public class COperation : Operation {

		public CodeModel.DataAggregate data;
		public CodeModel.UCOperation invoked;
		public CodeModel.UCOperation returnTo;

		public COperation(){

		}

		~COperation(){

		}

	}//end COperation

}//end namespace CodeModel