///////////////////////////////////////////////////////////
//  DataAggregate.cs
//  Implementation of the Class DataAggregate
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:54
//  Original author: smial
///////////////////////////////////////////////////////////




using CodeModel;
namespace CodeModel {
	public class DataAggregate : NamedElement {

		public CodeModel.DataItem fields;
		public CodeModel.ViewFunction m_ViewFunction;

		public DataAggregate(){

		}

		~DataAggregate(){

		}

	}//end DataAggregate

}//end namespace CodeModel