///////////////////////////////////////////////////////////
//  DataItem.cs
//  Implementation of the Class DataItem
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:54
//  Original author: smial
///////////////////////////////////////////////////////////

using System.ComponentModel;

namespace CodeModel {
	public class DataItem : NamedElement {
		public string type;
		public TypeKind? typekind = null;

		public DataItem(){}

		public string ToCode(int tabs = 0){
			string ts = Utils.GetTabString(tabs);
			string code = ts + Utils.ToCamelCase(name) + ": ";
			if (TypeKind.Primitive != typekind) code += Utils.ToPascalCase(type) + (TypeKind.Simple == typekind ? "" : "[]");
			else {
				switch (type) {
					case "integer": code += "bigint";
					break;
					case "float": code += "number";
					break;
					case "text": code += "string";
					break;
					case "boolean": code += "boolean";
					break;
					case "time":
					case "date": code += "Date";
					break;
				}
			}
			return code + ";";
		}
	}

	public enum TypeKind {
		Primitive,
		Simple,
		Multiple
	}
}