///////////////////////////////////////////////////////////
//  Decision.cs
//  Implementation of the Class Decision
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:54
//  Original author: smial
///////////////////////////////////////////////////////////




using CodeModel;
namespace CodeModel {
	public class Decision : Instruction {

		public CodeModel.Condition conditions;

		public Decision(){

		}

		~Decision(){

		}

	}//end Decision

}//end namespace CodeModel