///////////////////////////////////////////////////////////
//  End.cs
//  Implementation of the Class End
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:54
//  Original author: smial
///////////////////////////////////////////////////////////

using CodeModel;
namespace CodeModel {
	public class End : Instruction {
        public Value value = null;
		public End(){}

        public override string ToCode(int tabs = 0){
            string ts = Utils.GetTabString(tabs);
            string code = ts + "if (null != returnTo)\n";
            code += ts + "\tthis.returnTo(" + value.parent.GetElemName() + "." + value.GetElemName() + ");";
            return code;
        }
    }
}