///////////////////////////////////////////////////////////
//  EnumUnion.cs
//  Implementation of the Class EnumUnion
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:54
//  Original author: smial
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Linq;
namespace CodeModel {
	public class EnumUnion : NamedElement {
		public List<CheckEnumeration> elements = new List<CheckEnumeration>();

		public EnumUnion(){}

		public string GetElemName(){
            return Utils.ToPascalCase(name.Replace("@","at").Replace("!", ""));
        }

		public string GetVarName(){
            return Utils.ToCamelCase(name.Replace("@","at").Replace("!", ""));
        }

		public string ToCode(int tabs = 0){
			string ts = Utils.GetTabString(tabs);
			string code = ts + "export type " + GetElemName() + " = \n\t";
			code += string.Join("\n\t| ", elements.Select(e => ts + e.GetElemName() )) + "\n";
			code += ts + "\t;\n";
			return code;
		}
	}
}