///////////////////////////////////////////////////////////
//  Enumeration.cs
//  Implementation of the Class Enumeration
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:54
//  Original author: smial
///////////////////////////////////////////////////////////




using CodeModel;
namespace CodeModel {
	public class Enumeration : NamedElement {

		public CodeModel.Value values;

		public Enumeration(){

		}

		~Enumeration(){

		}

	}//end Enumeration

}//end namespace CodeModel