///////////////////////////////////////////////////////////
//  Expression.cs
//  Implementation of the Class Expression
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:54
//  Original author: smial
///////////////////////////////////////////////////////////




using CodeModel;
namespace CodeModel {
	public class Expression {

		public CodeModel.DataAggregate data;
		public CodeModel.Value value;

		public Expression(){

		}

		~Expression(){

		}

	}//end Expression

}//end namespace CodeModel