///////////////////////////////////////////////////////////
//  Expression.cs
//  Implementation of the Class Expression
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:54
//  Original author: smial
///////////////////////////////////////////////////////////

namespace CodeModel {
	public class Expression {
		public DataAggregate data;
		public Value value;

		public Expression(){}

		public string ToCode(){
			// CODE: ClientEnumCheck.Valid == clientEnumCheck
			return data == null ? "result == \"" + value.GetElemName() + "\""
						: data.enumer.GetElemName() + "." + value.GetElemName() + " == " + data.enumer.GetVarName();
        }
	}
}