///////////////////////////////////////////////////////////
//  FileGenerator.cs
//  Implementation of the Class FileGenerator
//  Generated by Enterprise Architect
//  Created on:      31-sty-2024 11:38:36
//  Original author: smial
///////////////////////////////////////////////////////////

using System.IO;

namespace CodeModel {
	public abstract class FileGenerator : Generator {
		public FileGenerator(){}

		public void ToFile(string path){
			if (!Directory.Exists(path)) Directory.CreateDirectory(path);
			File.WriteAllText(path + "\\" + Utils.ToPascalCase(GetFileName()) + ".ts", ToCode());
		}

		protected abstract string GetFileName();
	}
}