///////////////////////////////////////////////////////////
//  Generator.cs
//  Implementation of the Class Generator
//  Generated by Enterprise Architect
//  Created on:      31-sty-2024 11:38:39
//  Original author: smial
///////////////////////////////////////////////////////////

namespace CodeModel {
	public abstract class Generator : NamedElement {
		public Generator(){}

		public abstract string ToCode(int tabs = 0);
		public abstract string GetElemName();
	}
}