///////////////////////////////////////////////////////////
//  Instruction.cs
//  Implementation of the Class Instruction
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////




namespace CodeModel {
	public abstract class Instruction {

		private string label;

		public Instruction(){

		}

		~Instruction(){

		}

	}//end Instruction

}//end namespace CodeModel