///////////////////////////////////////////////////////////
//  NamedElement.cs
//  Implementation of the Class NamedElement
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////




namespace CodeModel {
	public class NamedElement {

		public NamedElement(){

		}

		~NamedElement(){

		}

	}//end NamedElement

}//end namespace CodeModel