///////////////////////////////////////////////////////////
//  Operation.cs
//  Implementation of the Class Operation
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////




using CodeModel;
namespace CodeModel {
	public class Operation : NamedElement {

		public string returnType;
		public CodeModel.DataItem parameters;

		public Operation(){

		}

		~Operation(){

		}

	}//end Operation

}//end namespace CodeModel