///////////////////////////////////////////////////////////
//  DataItem.cs
//  Implementation of the Class DataItem
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:54
//  Original author: smial
///////////////////////////////////////////////////////////

namespace CodeModel {
	public class Parameter {
		public string type;

		public Parameter(){}

		public string ToCode(int i = 0, bool var = false){
			string code = Utils.ToCamelCase(type) + (i>0 ? i.ToString() : "");
			if (!var) code += ": " + Utils.ToPascalCase(type);
			return code;
		}

		public string ToVarCode(int i = 0){
			return ToCode(i, true);
		}
	}
}