///////////////////////////////////////////////////////////
//  POperation.cs
//  Implementation of the Class POperation
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////

using CodeModel;
namespace CodeModel {
	public class POperation : UCCallableOperation {
		public POperation(){}
		
		public override string ToCode(){
            throw new System.NotImplementedException();
        }
	}
}