///////////////////////////////////////////////////////////
//  POperation.cs
//  Implementation of the Class POperation
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////

using CodeModel;
namespace CodeModel {
	public class POperation : UCCallableOperation {
        public PresenterClass pres = null;
		public POperation(){}

        public override string GetElemName(){
            return Utils.ToCamelCase(name.Replace("!", ""));
        }

        public override string ToCode(int tabs){
			string ts = Utils.GetTabString(tabs);
            string code = ts + GetElemName() + GetParametersCode() + "{\n";
            foreach (Parameter da in parameters)
                code += ts + "\tthis.state." + da.ToVarCode() + " = " + da.ToVarCode() + ";\n";
            code += ts + "\tthis.gUpdateView?.(ScreenId." + pres.GetElemName().ToUpper().Substring(1) + ");\n" + ts + "}";
            return code;
        }
	}
}