///////////////////////////////////////////////////////////
//  POperation.cs
//  Implementation of the Class POperation
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////

using CodeModel;
namespace CodeModel {
	public class POperation : UCCallableOperation {
		public POperation(){}

        public override string GetElemName(){
            return Utils.ToCamelCase(name.Replace("!", ""));
        }

        public override string ToCode(int tabs){
			string ts = GetTabString(tabs);
            throw new System.NotImplementedException();
        }
	}
}