///////////////////////////////////////////////////////////
//  PresenterClass.cs
//  Implementation of the Class PresenterClass
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////

using System.Collections.Generic;
namespace CodeModel {
	public class PresenterClass : ClassFileGenerator {
		public List<POperation> methods = new List<POperation>();

		public PresenterClass(){}

        public override string GetElemName(){
            return "P" + Utils.ToPascalCase(name);
        }

        public override string GetVarName(){
            return "p" + Utils.ToPascalCase(name);
        }

        public override string ToCode(int tabs){
		    string ts = GetTabString(tabs);
            throw new System.NotImplementedException();
        }

        protected override string GetFileName(){
            return "P " + name;
        }
    }
}