///////////////////////////////////////////////////////////
//  PresenterClass.cs
//  Implementation of the Class PresenterClass
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Linq;
namespace CodeModel {
	public class PresenterClass : ClassFileGenerator {
		public List<POperation> methods = new List<POperation>();

		public PresenterClass(){}

        public override string GetElemName(){
            return "P" + Utils.ToPascalCase(name);
        }

        public override string GetVarName(){
            return "p" + Utils.ToPascalCase(name);
        }

        private string GetImports(){
            string code = "import { Dispatch } from \"react\";\n";
            code += "import { PresentationDispatcher } from \"./PresentationDispatcher\";\n";
            
            code += "import { ";
            List<string> dataObjects = new List<string>();
            dataObjects.Add(GetElemName().Substring(1) + "State");
            dataObjects.Add("ScreenId");
            foreach (POperation cop in methods){
                if (null != cop.returnType && "boolean" != cop.returnType) dataObjects.Add(cop.GetReturnTypeElemName());
                foreach (Parameter par in cop.parameters) {
                    string name = par.ToTypeCode();
                    if (!dataObjects.Contains(name)) dataObjects.Add(name);
                }
            }
            code += string.Join(", ", dataObjects);
            code += " } from \"../../viewmodel/ViewModel\";\n";
            
            return code + "\n";
        }

        public override string ToCode(int tabs){
		    string ts = Utils.GetTabString(tabs);
            string code = "";
            if ("presentation dispatcher" == name){
                code += "import { ScreenId } from \"../../viewmodel/ViewModel\";\n";
                code += "import { Dispatch } from \"react\";\n\n";
                code += "export class PresentationDispatcher {\n";
                code += "\tgUpdateView!: Dispatch<ScreenId>;\n";
                code += "\tinjectGlobalUpdateView(guv: Dispatch<ScreenId>) {\n";
                code += "\t\tthis.gUpdateView = guv;\n";
                code += "\t}\n}\n";
                return code;
            }
            code = GetImports();
            // export function updateClwView(state: ClientListWndData, action: string) {
            code += ts + "export function update" + Utils.ToPascalCase(name) + "(";
            code += "state: " + Utils.ToPascalCase(name) + "State, action: string) {\n";
            //   let newState = { ...state };
            code += ts + "\tlet newState = { ...state };\n";
            //   return newState;
            code += ts + "\treturn newState;\n" + ts + "}\n\n";
            // }

            // CODE: export class PClientListWnd extends PresentationDispatcher {
            code += ts + "export class " + GetElemName() + " extends PresentationDispatcher {\n";
            //   CODE: state!: ClientListWndData;
            code += ts + "\tstate!: " + Utils.ToPascalCase(name) + "State;\n";
            //   CODE: updateView!: Dispatch<string>;
            code += ts + "\tupdateView!: Dispatch<string>;\n\n";

            code += ts + "\tinjectStateHandle(state: " + Utils.ToPascalCase(name) + "State, updateView: Dispatch<string>) {\n";
            code += ts + "\t\tthis.state = state;\n";
            code += ts + "\t\tthis.updateView = updateView;\n";
            code += ts + "\t}\n\n";

            code += string.Join("\n", methods.Select(m => m.ToCode(tabs + 1)+"\n"));

            code += ts + "}";

            return code;
        }

        protected override string GetFileName(){
            return ("presentation dispatcher" == name ? "" : "P ") + name;
        }
    }
}