///////////////////////////////////////////////////////////
//  ServiceInterface.cs
//  Implementation of the Class ServiceInterface
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Linq;
namespace CodeModel {
	public class ServiceInterface : FileGenerator {
		public List<SOperation> signatures = new List<SOperation>();

		public ServiceInterface(){}

        public override string ToCode(){
            string code = "export interface I" + Utils.ToPascalCase(name) + " {\n";
            code += string.Join(";\n",signatures.Select(x => x.ToCode()));
            code += ";\n}";
            return code;
        }
    }
}