///////////////////////////////////////////////////////////
//  ServiceInterface.cs
//  Implementation of the Class ServiceInterface
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////




using CodeModel;
namespace CodeModel {
	public class ServiceInterface : NamedElement {

		public CodeModel.SOperation signatures;

		public ServiceInterface(){

		}

		~ServiceInterface(){

		}

	}//end ServiceInterface

}//end namespace CodeModel