///////////////////////////////////////////////////////////
//  SOperation.cs
//  Implementation of the Class SOperation
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////

namespace CodeModel {
	public class SOperation : UCCallableOperation {
		public SOperation(){}

		public override string ToCode(){
			string code = Utils.ToCamelCase(name.Replace("!", "")) + GetParametersCode();
			return code;
        }
	}
}