///////////////////////////////////////////////////////////
//  SOperation.cs
//  Implementation of the Class SOperation
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////




using CodeModel;
namespace CodeModel {
	public class SOperation : UCCallableOperation {

		public SOperation(){

		}

		~SOperation(){

		}

	}//end SOperation

}//end namespace CodeModel