///////////////////////////////////////////////////////////
//  Trigger.cs
//  Implementation of the Class Trigger
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////

namespace CodeModel {
	public class Trigger : NamedElement {
		public COperation action;
		public COperation condition;
		public string type = "button";
        public string label = null;

		public Trigger(){}

        public string ToCode(int tabs) {
 			string ts = Utils.GetTabString(tabs);
            string code = ts + "<button\n"; // TODO - handle different types of buttons (links, etc.)
			if (null != condition) code += ts + "\tdisabled={!Boolean(" + condition.GetElemName() + "())}\n";
			code += ts + "\tonClick={" + action.GetElemName() + "}\n" + ts + ">\n";
			code += ts + "\t" + Utils.ToTitleCase(name) + "\n" + ts + "</button>"; // TODO - as above
			return code;
        }
    }
}