///////////////////////////////////////////////////////////
//  Trigger.cs
//  Implementation of the Class Trigger
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////




using CodeModel;
namespace CodeModel {
	public class Trigger : NamedElement {

		public CodeModel.COperation action;
		public CodeModel.COperation condition;

		public Trigger(){

		}

		~Trigger(){

		}

	}//end Trigger

}//end namespace CodeModel