///////////////////////////////////////////////////////////
//  Trigger.cs
//  Implementation of the Class Trigger
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////

namespace CodeModel {
	public class Trigger : NamedElement {
		public COperation action;
		public COperation condition;

		public Trigger(){}

        public string ToCode(int tabs) {
 			string ts = Utils.GetTabString(tabs);
            string code = ts + "<button\n" + ts + "\tonClick={" + action.GetElemName() + "}\n" + ts + ">\n";
			code += ts + "\t" + Utils.ToTitleCase(name) + "\n" + ts + "</button>";
			return code;
        }
    }
}