///////////////////////////////////////////////////////////
//  UCCallableOperation.cs
//  Implementation of the Class UCCallableOperation
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////




using CodeModel;
namespace CodeModel {
	public class UCCallableOperation : Operation {

		public UCCallableOperation(){

		}

		~UCCallableOperation(){

		}

	}//end UCCallableOperation

}//end namespace CodeModel