///////////////////////////////////////////////////////////
//  UCCallableOperation.cs
//  Implementation of the Class UCCallableOperation
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////

namespace CodeModel {
	public abstract class UCCallableOperation : Operation {
		public UCCallableOperation(){}
	}
}