///////////////////////////////////////////////////////////
//  UCOperation.cs
//  Implementation of the Class UCOperation
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////

using System.Collections.Generic;
namespace CodeModel {
	public class UCOperation : Operation {
		public List<Instruction> instructions = new List<Instruction>();
		public UseCaseClass uc = null;

		public UCOperation(){}
		
		public override string ToCode(int tabs){
			string ts = GetTabString(tabs);
            throw new System.NotImplementedException();
        }
	}
}