///////////////////////////////////////////////////////////
//  UseCaseClass.cs
//  Implementation of the Class UseCaseClass
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////

using System.Collections.Generic;
namespace CodeModel {
	public class UseCaseClass : FileGenerator {
		public List<UCOperation> methods = new List<UCOperation>();
		public List<PresenterClass> presenters = new List<PresenterClass>();
		public List<ServiceInterface> services = new List<ServiceInterface>();

		public UseCaseClass(){}

        public override string ToCode(){
            throw new System.NotImplementedException();
        }
    }
}