///////////////////////////////////////////////////////////
//  UseCaseClass.cs
//  Implementation of the Class UseCaseClass
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////




using CodeModel;
namespace CodeModel {
	public class UseCaseClass : NamedElement {

		public CodeModel.UCOperation methods;
		public CodeModel.PresenterClass presenters;
		public CodeModel.ServiceInterface services;

		public UseCaseClass(){

		}

		~UseCaseClass(){

		}

	}//end UseCaseClass

}//end namespace CodeModel