///////////////////////////////////////////////////////////
//  Value.cs
//  Implementation of the Class Value
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////

namespace CodeModel {
	public class Value : NamedElement {

		public Value(){
		}

		public string GetElemName(){
			return Utils.ToUpperCase(name);
		}
	}
}