///////////////////////////////////////////////////////////
//  Value.cs
//  Implementation of the Class Value
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////




using CodeModel;
namespace CodeModel {
	public class Value : NamedElement {

		public Value(){

		}

		~Value(){

		}

	}//end Value

}//end namespace CodeModel