///////////////////////////////////////////////////////////
//  ViewFunction.cs
//  Implementation of the Class ViewFunction
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////




using CodeModel;
namespace CodeModel {
	public class ViewFunction : NamedElement {

		public CodeModel.DataAggregate data;
		public CodeModel.ControllerFunction controller;
		public CodeModel.PresenterClass presenter;
		public CodeModel.Trigger triggers;

		public ViewFunction(){

		}

		~ViewFunction(){

		}

	}//end ViewFunction

}//end namespace CodeModel