///////////////////////////////////////////////////////////
//  ViewModel.cs
//  Implementation of the Class ViewModel
//  Generated by Enterprise Architect
//  Created on:      23-sty-2024 15:01:55
//  Original author: smial
///////////////////////////////////////////////////////////

using System.Collections.Generic;
namespace CodeModel {
	public class ViewModel {
		public List<DataAggregate> items = new List<DataAggregate>();
		public List<CheckEnumeration> enums = new List<CheckEnumeration>();

		public ViewModel(){}
	}
}